#!/bin/sh /etc/rc.common

START=95
STOP=10
USE_PROCD=1

start_service() {
	local enabled
	config_load nuitguard
	config_get_bool enabled main enabled 0
	[ "$enabled" -eq 1 ] || return 0
	procd_open_instance
	procd_set_param command /usr/sbin/nuitguard run
	procd_set_param respawn 3600 60 3
	procd_set_param term_timeout 150
	procd_set_param stdout 0
	procd_set_param stderr 0
	procd_close_instance
}

reload_service() {
	stop
	start
}

service_stopped() {
	/usr/sbin/nuitguard restore
}
